name: molecule_core
description: Core data structures and utilities for chemistry software.
version: 0.0.1
repository: https://github.com/afstanton/molecule_core

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
